apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitsong
  namespace: bitsong-fullnode
spec:
  serviceName: bitsong-headless
  replicas: 1
  selector:
    matchLabels:
      app: bitsong
  template:
    metadata:
      labels:
        app: bitsong
    spec:
      terminationGracePeriodSeconds: 120

      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
          command: ["/bin/sh", "-lc"]
          args:
            - |
              set -eu
              mkdir -p /data/.bitsongd
              chown -R 1000:1000 /data
              chmod -R g+rwX /data
          volumeMounts:
            - name: data
              mountPath: /data

        - name: init-bitsong
          image: mycuriosity/bitsong 
          imagePullPolicy: IfNotPresent
          workingDir: /data/.bitsongd
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          command: ["/bin/sh", "-lc"]
          env:
            - name: HOME
              value: "/data"
            - name: CHAIN_ID
              value: "bitsong-2b"
            - name: MONIKER
              value: "bitsong-gke"
            - name: SNAPSHOT_URL
              value: "https://snapshots.polkachu.com/snapshots/bitsong/	bitsong_26228249.tar.lz4"
          args:
            - |
              set -eu
              sh /scripts/init.sh
          volumeMounts:
            - name: data
              mountPath: /data
            - name: init-scripts
              mountPath: /scripts

      containers:
        - name: bitsong
          image: mycuriosity/bitsong
          imagePullPolicy: IfNotPresent
          workingDir: /data/.bitsongd
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          command: ["bitsongd"]
          args: ["start", "--home", "/data/.bitsongd"]
          ports:
            - name: p2p
              containerPort: 26656
            - name: rpc
              containerPort: 26657
            - name: rest
              containerPort: 1317
            - name: prom
              containerPort: 26660
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          startupProbe:
            httpGet:
              path: /status
              port: 26657
            failureThreshold: 60
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /status
              port: 26657
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 26657
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data

      volumes:
        - name: init-scripts
          configMap:
            name: bitsong-init
            defaultMode: 0444

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard-rwo
        resources:
          requests:
            storage: 10Gi
