apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader
  namespace: bitsong-fullnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reloader
  template:
    metadata:
      labels:
        app: reloader
    spec:
      serviceAccountName: reloader
      containers:
        - name: reloader
          image: ghcr.io/stakater/reloader:v1.0.62
          imagePullPolicy: IfNotPresent
          args:
            - --reload-strategy=annotations
            - --sync-after-restart
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reloader
  namespace: bitsong-fullnode

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reloader-role
  namespace: bitsong-fullnode
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reloader-role-binding
  namespace: bitsong-fullnode
subjects:
  - kind: ServiceAccount
    name: reloader
    namespace: bitsong-fullnode
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reloader-role