apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitsong
  namespace: bitsong-fullnode
spec:
  serviceName: bitsong-headless
  replicas: 1

  selector:
    matchLabels:
      app: bitsong

  template:
    metadata:
      labels:
        app: bitsong
      annotations:
        reloader.stakater.com/match: "true"

    spec:
      terminationGracePeriodSeconds: 120

      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      ############################################################
      # INIT CONTAINERS
      ############################################################
      initContainers:

        # 1) Fix permissions on PVC
        - name: fix-permissions
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
          command: ["/bin/sh", "-lc"]
          args:
            - |
              set -eu
              mkdir -p /data/.bitsongd
              chown -R 1000:1000 /data
              chmod -R g+rwX /data
          volumeMounts:
            - name: data
              mountPath: /data

        # 2) Bitsong init (home / genesis / peers / snapshot)
        - name: init-bitsong
          image: mycuriosity/bitsong
          imagePullPolicy: IfNotPresent
          workingDir: /data/.bitsongd
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          command: ["/bin/sh", "-lc"]
          args:
            - /scripts/init.sh
          env:
            - name: CHAIN_ID
              value: "bitsong-2b"
            - name: MONIKER
              value: "bitsong-gke"
            - name: POLKACHU_SECRET
              valueFrom:
                secretKeyRef:
                  name: polkachu-secret
                  key: POLKACHU_SECRET
          volumeMounts:
            - name: data
              mountPath: /data
            - name: init-scripts
              mountPath: /scripts
              readOnly: true

      ############################################################
      # MAIN CONTAINER
      ############################################################
      containers:
        - name: bitsong
          image: mycuriosity/bitsong
          imagePullPolicy: IfNotPresent
          workingDir: /data/.bitsongd
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          command: ["bitsongd"]
          args:
            - start
            - --home
            - /data/.bitsongd
          ports:
            - name: p2p
              containerPort: 26656
            - name: rpc
              containerPort: 26657
            - name: rest
              containerPort: 1317
            - name: prom
              containerPort: 26660
          volumeMounts:
            - name: data
              mountPath: /data

      ############################################################
      # VOLUMES
      ############################################################
      volumes:
        - name: init-scripts
          configMap:
            name: bitsong-init
            defaultMode: 0755

  ############################################################
  # PVC TEMPLATE
  ############################################################
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard-rwo
        resources:
          requests:
            storage: 10Gi
