apiVersion: v1
kind: Service
metadata:
  name: bitsong-lb
  namespace: bitsong-fullnode
spec:
  type: LoadBalancer
  selector:
    app: bitsong
  ports:
    - name: p2p
      port: 26656
      targetPort: 26656
    - name: rpc
      port: 26657
      targetPort: 26657
    - name: rest
      port: 1317
      targetPort: 1317
    - name: prom
      port: 26660
      targetPort: 26660