apiVersion: v1
kind: Service
metadata:
  name: bitsong-headless
  namespace: bitsong-fullnode
spec:
  clusterIP: None
  selector:
    app: bitsong
  ports:
    - name: p2p
      port: 26656
      targetPort: 26656
    - name: rpc
      port: 26657
      targetPort: 26657